### PR TITLE
Drop 0.7 and change REQUIRE to Project.toml

### PR DESCRIPTION
**Pull request by abelsiqueira**

### CODE REVIEW

**Comment by dpo** [comment]
Remove `Pkg.clone(pwd())` from `.travis.yml`.

**Comment by dpo** [comment]
Also change `Pkg.build("LDLFactorizations"); Pkg.test("LDLFactorizations"; coverage=true)` to `Pkg.build(); Pkg.test(; coverage=true)`.

**Comment by abelsiqueira** [comment]
I simplified it more, it uses the default `script:` and `before_install:` now.

**Comment by dpo** [comment]
Thank you!

**Pull request merged**
