### PR TITLE
Optimized ldl_solve! for multiple rhs

### PR DESCRIPTION
**Pull request by amontoison**

### CODE REVIEW

**Comment by amontoison** [comment]
https://gist.github.com/amontoison/473b69f3e170dde2018cf48039b4edd2

**Comment by dpo** [comment]
What is being compared here?

ps: the TravisCI build disappeared!

**Comment by amontoison** [comment]
I used the `run_benchmarks.jl` file inside the benchmark folder to compare this commit with the master branch.
The modifications only concern the `solve5` testset.

**Comment by amontoison** [comment]
I have some small differences with `fact` and `solve1` testsets because I was using the computer in the same time.

**Comment by dpo** [comment]
This is a good option because the code looks like the one in #53. Let's take it. Thank you. I'll just close and reopen to see if TravisCI accepts to run.

**Pull request merged**
