### PR TITLE
Analyze factorize

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by dpo** [comment]
@CelestineAngla I tried to imitate your design, but I would rather use separate structs for the symbolic and numerical data. Unfortunately, the current design duplicates P (the permutation) and Lp (the pointers to the beginning of each column of the L factor). Any suggestion on how to improve?

**Comment by CelestineAngla** [comment]
Could we just have a pointer to P and Lp in the numerical structure ?

**Comment by dpo** [comment]
Now using a single combined structure for analysis / factorization. Works for both `Symmetric{}` and "regular" matrices. Dense arrays are converted to sparse. Non-`Symmetric{}` matrices are assumed to contain both triangles.

**Comment by dpo** [comment]
https://gist.github.com/dpo/b60158787038214945caa8e3daaff580

**Comment by dpo** [comment]
Updated benchmarks: https://gist.github.com/dpo/b3494f79d9c622db0142c0de11ac428c

**Review by abelsiqueira — CHANGES_REQUESTED** [review]
I haven't checked the implementation details, but I'm happy with the results.
Since my corrections are small, I recommend using the `commit suggestion` GitHub feature and Squashing the merge afterwards.

**Pull request merged**
