### PR TITLE
travis-ci.org -> travis-ci.com

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by dpo** [comment]
@JSOBot runbenchmarks

**Comment by dpo** [comment]
@JSOBot runbenchmarks

**Comment by dpo** [comment]
@JSOBot runbenchmarks

**Comment by abelsiqueira** [comment]
:eyes:

**Comment by dpo** [comment]
@JSOBot runbenchmarks

**Comment by dpo** [comment]
@JSOBot runbenchmarks

**Comment by MonssafToukal** [comment]
@JSOBot runbenchmarks

**Comment by dpo** [comment]
@JSOBot runbenchmarks

**Comment by MonssafToukal** [comment]
@JSOBot runbenchmarks

**Comment by MonssafToukal** [comment]
@JSOBot runbenchmarks

**Comment by MonssafToukal** [comment]
@JSOBot runbenchmarks

**Comment by dpo** [comment]
@JSOBot runbenchmarks

**Comment by dpo** [comment]
@JSOBot runbenchmarks sqd_bmark

**Comment by dpo** [comment]
It didn't run the correct script.

**Pull request closed without merging**
